# Generated by Django 2.1.2 on 2018-11-03 06:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumname_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='True', upload_to=blog.models.user_path),
        ),
    ]
