# Generated by Django 2.1.2 on 2018-11-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181103_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='True', upload_to='post'),
        ),
    ]
